memeapp/controllers/memes.py
from flask import g, render_template, request, redirect, Response, send_file, Blueprint, current_app, jsonify
from selenium import webdriver
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.chrome.service import Service
import json

from memeapp.utils.dbutils import db_query, db_execute, get_user_id_by_username
from memeapp.controllers.users import login_required
from memeapp.model import Meme
import os

bp = Blueprint("memes", __name__)


def get_driver():
    """Sets chrome options for Selenium.
    Chrome options for headless browser is enabled.
    See https://nander.cc/using-selenium-within-a-docker-container
    """
    service = Service(executable_path="/usr/bin/chromedriver")
    chrome_options = Options()
    chrome_options.add_argument("--headless")
    chrome_options.add_argument("--no-sandbox")
    chrome_options.add_argument("--disable-dev-shm-usage")
    # chrome_options.experimental_options["prefs"] = chrome_prefs
    # chrome_prefs["profile.default_content_settings"] = {"images": 2}
    return webdriver.Chrome(options=chrome_options, service=service)


def save_meme(file, name):
    ext = file.filename.rsplit(".")[-1]
    if "." in file.filename and len(ext) < 6 and not name.endswith(ext):
        name += "." + ext
    file_id = db_execute("INSERT INTO memes(name, owner) VALUES (?, ?)", (name, g.user.id))
    path = os.path.normpath(os.path.join(current_app.config['UPLOAD_DIRECTORY'], name))
    if not os.path.exists(path):
        file.save(path)
    return file_id


@bp.route("/upload", methods=["GET", "POST"])
@login_required
def upload_meme():
    if request.method == "POST":
        if 'file' not in request.files or 'name' not in request.form:
            return redirect("/upload")
        file = request.files['file']
        if file.filename == '':
            return redirect("/upload")
        if file:
            name = request.form.get("name")
            file_id = save_meme(file, name)
            return redirect(f"/memes/{file_id}")
        else:
            return redirect("/upload")

    return render_template("upload.html", user=g.user)


@bp.route("/import", methods=["POST"])
@login_required
def import_meme():
    url = request.form.get("url")
    name = request.form.get("name")
    if not name.endswith(".png"):
        name = name + ".png"
    driver = get_driver()
    driver.get(url)
    file_id = db_execute("INSERT INTO memes(name, owner) VALUES (?, ?)", (name, g.user.id))
    driver.save_screenshot(os.path.normpath(os.path.join(current_app.config['UPLOAD_DIRECTORY'], name)))
    return redirect(f"/memes/{file_id}")


@bp.route("/memes/<meme_id>/view", methods=["GET"])
@login_required
def get_meme(meme_id):
    def get_mimetype(fname):
        if fname.endswith(".png"):
            return "image/png"
        elif fname.endswith(".jpeg") or fname.endswith(".jpg"):
            return "image/jpeg"
        else:
            return "image/svg+xml"

    result = db_query("SELECT name, owner FROM memes WHERE rowid=?", (meme_id,), one=True)
    if not result:
        return Response("Not Found", status=404)
    name, u = result
    shared = map(lambda x: x[0], db_query("SELECT user FROM meme_shares WHERE meme=?", (meme_id,), one=False))
    valid_users = {u, *shared}
    if u not in valid_users:
        return Response("Not Found", status=404)
    return send_file(os.path.join(current_app.config['UPLOAD_DIRECTORY'], name),
                     mimetype=get_mimetype(name))


@bp.route("/memes/<meme_id>", methods=["GET"])
@login_required
def view_meme(meme_id):
    result = db_query("SELECT name, owner FROM memes WHERE rowid=?", (meme_id,), one=True)
    if not result:
        return Response("Not Found", status=404)
    name, u = result
    shared = map(lambda x: x[0], db_query("SELECT user FROM meme_shares WHERE meme=?", (meme_id,), one=False))
    valid_users = {u, *shared}
    if g.user.id not in valid_users:
        return Response("Not Found", status=404)
    return render_template("meme.html", meme=Meme(id=meme_id, name=name, owner=g.user), user=g.user, nonce=g.nonce)


@bp.route("/memes/<meme_id>/shares", methods=["POST"])
@login_required
def share_meme(meme_id):
    result = db_query("SELECT name, owner FROM memes WHERE rowid=?", (meme_id,), one=True)
    if not result:
        return Response("Not Found", status=404)
    name, owner_id = result
    if owner_id != g.user.id:
        return Response("Not Found", status=404)
    data = json.loads(request.data.decode("UTF-8"))
    if 'username' not in data:
        return Response("Bad Request", status=400)
    username = data['username']
    user_id = get_user_id_by_username(username)
    if not user_id:
        return Response("Bad Request", status=400)
    db_execute("INSERT INTO meme_shares VALUES (?, ?)", (user_id, meme_id))
    return Response("Created", status=201)


@bp.route("/memes/<meme_id>/comments", methods=["POST", "GET"])
@login_required
def comments(meme_id):
    result = db_query("SELECT name, owner FROM memes WHERE rowid=?", (meme_id,), one=True)
    if not result:
        return Response("Not Found", status=404)
    name, u = result
    shared = map(lambda x: x[0], db_query("SELECT user FROM meme_shares WHERE meme=?", (meme_id,), one=False))
    valid_users = {u, *shared}
    if g.user.id not in valid_users:
        return Response("Not Found", status=404)

    if request.method == "GET":
        meme_comments = db_query("SELECT title, author, body FROM comments WHERE meme=? ORDER BY rowid DESC",
                                 (meme_id,))
        user_ids_in_memes = (",".join(list(set([str(x[1]) for x in meme_comments]))))

        # TODO?
        sql = f"SELECT rowid, username FROM users WHERE rowid in ({user_ids_in_memes})"
        usernames = db_query(sql)
        usernames = {x[0]: x[1] for x in usernames}

        return jsonify(
            {"comments": list(
                map(lambda x: {
                    "title": x[0],
                    "author": {"id": str(x[1]),
                               "username": usernames[x[1]]
                               },
                    "body": x[2]},
                    meme_comments))})
    else:
        data = request.json
        author = g.user.id
        title = data["title"][:500]
        body = data["body"][:5000]
        row_id = db_execute("INSERT INTO comments(title, author, meme, body) VALUES(?,?,?,?)",
                            (title, author, meme_id, body))
        return Response(str(row_id), status=201)

memeapp/controllers/users.py
# import os
from flask import Blueprint, request, render_template, redirect, Response, g, url_for
from memeapp.model import User
from memeapp.utils import cryptoutils
from memeapp.utils.dbutils import db_query, db_execute, get_user_id_and_passhash_by_username
from memeapp.utils.authutils import set_session_token, login_required, clear_session_token

bp = Blueprint("users", __name__)


@bp.route("/login", methods=["GET", "POST"])
def login():
    if request.method == "GET":
        return redirect("/")
    # Try to protect from CSRF attack by validating remote_addr
    if request.remote_addr != '127.0.0.1' and request.remote_addr != '172.17.0.1':
        return redirect("/?error=Invalid+Site")
    username = request.form.get("username", None)
    password = request.form.get("password", None)
    user = get_user_id_and_passhash_by_username(username)
    # user = db_query(f"SELECT rowid, password_hash FROM users WHERE username=?", (username,), one=True)
    if user:
        user_id = user["id"]
        password_hash = user["password_hash"]
        if cryptoutils.check_password(password, password_hash):
            response = redirect("/")
            set_session_token(user_id, response)
            return response
        else:
            return redirect("/?error=Invalid+login")
    else:
        return redirect("/?error=Invalid+login")


@bp.route("/logout", methods=["GET"])
def logout():
    response = redirect("/") #TODO: target the sign in form rather than the sign up form
    clear_session_token(response)
    g.user = None
    return response

@bp.route("/users", methods=["GET", "POST"])
def create_edit_user():
    errors = []
    warnings = []
    infos = []
    successes = []

    # Try to protect from CSRF attack by validating remote_addr
    if request.remote_addr != '127.0.0.1' and request.remote_addr != '172.17.0.1':
        errors.append("Invalid site")

    username = request.form.get("username", None) #used for create, but not edit
    name = request.form.get("name", None)
    password = request.form.get("password", None)
    passwordConfirm = request.form.get("passwordConfirm", None)
    currentPassword = request.form.get("currentPassword", None) #used for create, but not edit

    is_admin = 0
    # This seems like a weird capability to make an admin via API call when you register
    # is_admin = int(request.form.get("a", 0))
    # if is_admin > 0:
    #     if not g.user or not g.user.is_admin:
    #         is_admin = 0

    # If there is no current user we assume that they are registering a new user vs editing an old one
    editing = not not g.user

    if not name:
        errors.append("Name is required")

    if editing:
        #Current password is required in order to change any information
        if currentPassword == None or currentPassword == "":
            errors.append("Please enter your current password")
        else:
            # user = db_query(f"SELECT password_hash FROM users WHERE username=?", (g.user.username,), one=True)
            user = get_user_id_and_passhash_by_username(g.user.username)
            if user:
                password_hash = user["password_hash"]
                if not cryptoutils.check_password(currentPassword, password_hash):
                    errors.append("Current password does not match what is on file.")

        # An empty "new" password is ok when editing.  
        # They do not need to change their password when they change their display name.  
        # If they do change their password they need to match
        emptyPassword = not password
        emptyConfirmPassword = not passwordConfirm or passwordConfirm == ''
        updatedPasswordsMatch = (password == passwordConfirm) or (emptyPassword and emptyConfirmPassword)
        if not updatedPasswordsMatch:
            errors.append("Passwords do not match")
    else:
        if username == None or username == "":
            errors.append("No username provided")
        if password == None or password == "":
            errors.append("Please choose a password")
        if password != passwordConfirm:
            errors.append("Passwords do not match")


    if len(errors) == 0:
        if editing:
            if password:
                pw_hash = cryptoutils.hash_password(password).decode("utf-8")
            else:
                pw_hash = None #Don't reset the password, let the COALESCE keep the password the same when they have only changes non-password related fields
            print("Attempting to update the user", name, pw_hash, g.user.id)
            db_execute("UPDATE users SET name = COALESCE(?, name), password_hash = COALESCE(?, password_hash) WHERE rowid=?",
                                p=(name, pw_hash, g.user.id))
            successes.append("User updated")
            #update the user visible fields
            g.user.name = name 
        else:  #Create the user
            print("Attempting to create the user")
            if isExistingUser(username):
                errors.append("Username is not available")
            else:
                pw_hash = cryptoutils.hash_password(password)
                user_id = db_execute("INSERT INTO users VALUES (?, ?, ?, ?)",
                                     p=(username, name, pw_hash.decode("utf-8"), is_admin))
                response = redirect("/home")
                set_session_token(user_id, response)

                return response
    if g.user:
        # TODO: return in a way that keeps form fields populated, rather than resets them
        return render_template("profile/editProfile.html", user=g.user, nonce=g.nonce, errors=errors, warnings=warnings, infos=infos, successes=successes)
    else:
        return render_template("authenticate.html", errors=errors, warnings=warnings, infos=infos, successes=successes)

def isExistingUser(userName):
    # existing_user = db_query("SELECT username FROM users WHERE username=?", p=(userName,), one=True)
    existing_user = get_user_id_and_passhash_by_username(userName)
    return not not existing_user

@bp.route("/users/<user_id>", methods=['GET'])
@login_required
def get_user(user_id=0):
    # Try to protect from CSRF attack by validating remote_addr
    if request.remote_addr != '127.0.0.1' and request.remote_addr != '172.17.0.1':
        return Response("Not found", 404)
    result = db_query("SELECT rowid, username, name FROM users WHERE rowid=?", (user_id,), True)
    if result and len(result) == 3:
        record_id, username, name = result
        user_record = {'id': record_id, 'username': username, 'name': name}

        memeCount = db_query("SELECT count(*) AS c FROM memes WHERE owner=?", (user_id,), True)
        commentCount = db_query("SELECT count(*) AS c FROM comments WHERE author=?", (user_id,), True)

        return render_template("profile/viewProfile.html", user=user_record, memeCount=memeCount[0], commentCount=commentCount[0])
    return Response("Not found", 404)

memeapp/templates/admin.html
{% extends "base.html" %}
{% block title %}Dank Memes{% endblock %}
{% block body %}
<div class="container-fluid p-5">
    <h2>
        Admin panel
    </h2>
    <h2>Settings</h2>
    <hr/>
    <table>
        <thead>
        <tr>
            <th>Name</th>
            <th>Value</th>
        </tr>
        </thead>
        <tbody>
        {% for name, value in settings.items() %}
        <tr>
            <th>{{ name }}</th>
            <th>{{ value }}</th>
        </tr>
        {% endfor %}
        </tbody>
    </table>
    <h2>Environment variables</h2>
    <hr/>
    <table>
        <thead>
        <tr>
            <th>Name</th>
            <th>Value</th>
        </tr>
        </thead>
        <tbody>
        {% for name, value in environ.items() %}
        <tr>
            <th>{{ name }}</th>
            <th>{{ value }}</th>
        </tr>
        {% endfor %}
        </tbody>
    </table>
</div>
{% endblock %}

memeapp/templates/authenticate.html
{% extends "base.html" %}
{% block title %}Dank Memes Application{% endblock %}
{% block menu %} <br/><br/>{% endblock %}
{% block body %}
<p>Welcome to the Dank Memes application! If you want to do meme, be dank.</p>
<ul class="nav nav-tabs" id="myTab" role="tablist">
    <li class="nav-item" role="presentation">
        <button class="nav-link active" id="home-tab" data-bs-toggle="tab" data-bs-target="#home-tab-pane" type="button"
                role="tab" aria-controls="home-tab-pane" aria-selected="true">Sign Up
        </button>
    </li>
    <li class="nav-item" role="presentation">
        <button class="nav-link" id="profile-tab" data-bs-toggle="tab" data-bs-target="#profile-tab-pane" type="button"
                role="tab" aria-controls="profile-tab-pane" aria-selected="false">Log In
        </button>
    </li>
</ul>
<div class="tab-content" id="myTabContent">
    <div class="tab-pane fade show active" id="home-tab-pane" role="tabpanel" aria-labelledby="home-tab" tabindex="0">
        <form class="p-2 rounded-bottom" action="/users" method="POST">
            <div class="mb-3">
                <label for="signupName" class="form-label required">Name</label>
                <input type="text" class="form-control" id="signupName" name="name">
            </div>
            <div class="mb-3">
                <label for="signupUsername" class="form-label required">Username</label>
                <input type="text" class="form-control" id="signupUsername" name="username">
            </div>
            <div class="mb-3">
                <label for="signupPassword" class="form-label required">Password</label>
                <input type="password" class="form-control" id="signupPassword" name="password">
            </div>
            <div class="mb-3">
                <label for="signupPassword2" class="form-label required">Confirm Password</label>
                <input type="password" class="form-control" id="signupPassword2" name="passwordConfirm">
            </div>
            <button type="submit" class="btn btn-primary" onClick="showLoading()">Create Account</button>
        </form>
    </div>
    <div class="tab-pane fade" id="profile-tab-pane" role="tabpanel" aria-labelledby="profile-tab" tabindex="1">
        <form class="p-2 rounded-bottom" action="/login" method="POST">
            <div class="mb-3">
                <label for="loginUsername" class="form-label">Username</label>
                <input type="text" class="form-control" id="loginUsername" name="username">
            </div>
            <div class="mb-3">
                <label for="loginPassword" class="form-label">Password</label>
                <input type="password" class="form-control" id="loginPassword" name="password">
            </div>
            <button type="submit" class="btn btn-primary" onClick="showLoading()">Log In</button>
        </form>
    </div>
</div>
{% endblock %}

memeapp/templates/base.html
<!doctype html>
<html lang="en" data-bs-theme="dark">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    {% block head %}
    <title>{% block title %}{% endblock %}</title>
    {% endblock %}
    <link rel="shortcut icon" href="{{ url_for('static', filename='favicon.ico') }}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
    <link rel= "stylesheet" type= "text/css" href= "{{ url_for('static',filename='css/loading.css') }}">
    <link rel= "stylesheet" type= "text/css" href= "{{ url_for('static',filename='css/main.css') }}">
    <script src= "{{ url_for('static',filename='js/loading.js') }}"></script>
</head>
<body>
<div class="container-fluid">
    {% block menu %}
    <div class="row">
        <div class="col-12">
            <nav class="navbar navbar-expand-lg bg-body-tertiary">
                <div class="container-fluid">
                    <a class="navbar-brand" href="/">Dank Memes</a>
                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                            data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                            aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="collapse navbar-collapse" id="navbarSupportedContent">
                        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                            <li class="nav-item">
                                <a class="nav-link" aria-current="page" href="/home">My Memes</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="/shared">Shared With Me</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="/upload">Upload Meme</a>
                            </li>
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown"
                                   aria-expanded="false">
                                    {{ g.user.username }}
                                </a>
                                <ul class="dropdown-menu">
                                    <li><a class="dropdown-item" href="/profile">Profile</a></li>
                                    <li>
                                        <hr class="dropdown-divider">
                                    </li>
                                    <li><a class="dropdown-item" href="/logout">Log out</a></li>
                                </ul>
                            </li>
                        </ul>
                        <form class="d-flex" role="search">
                            <input class="form-control me-2" id="search" name="search" type="search" placeholder="Search" aria-label="Search">
                            <button class="btn btn-outline-success" type="submit">Search</button>
                        </form>
                    </div>
                </div>
            </nav>
        </div>
    </div>
    {% endblock %}
    <div class="row">
        <div class="col-1"></div>
        <div class="col-10">
            {% if errors %}
                <div class="alert alert-danger" role="alert">
                    <ul class="error">
                        {% for error in errors %}
                            <li>{{error}}</li>
                        {% endfor %}
                    </ul>
                </div>
            {% endif %}
            {% if warnings %}
                <div class="alert alert-warning" role="alert">
                    <ul class="warning">
                        {% for warning in warnings %}
                            <li>{{warning}}</li>
                        {% endfor %}
                    </ul>
                </div>
            {% endif %}
            {% if infos %}
                <div class="alert alert-info" role="alert">
                    <ul class="info">
                        {% for info in infos %}
                            <li>{{info}}</li>
                        {% endfor %}
                    </ul>
                </div>
            {% endif %}
            {% if successes %}
                <div class="alert alert-primary" role="alert">
                    <ul class="success">
                        {% for success in successes %}
                            <li>{{success}}</li>
                        {% endfor %}
                    </ul>
                </div>
            {% endif %}
            {% block body %}
            {% endblock %}
        </div>
        <div class="col-1">
        </div>
    </div>
</div>

<div name="loading" id="loading" class="outPopUp hideLoading">
    <div class="spinner-border" role="status">
        <span class="visually-hidden">Loading...</span>
    </div></div>
<script src="{{ url_for('static',filename='js/hideLoading.js') }}"></script>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm"
        crossorigin="anonymous"></script>
</body>
</html>

memeapp/templates/home.html
{% extends "base.html" %}
{% block title %}Home{% endblock %}
{% block body %}
<div class="container-fluid">
    <div class="row row-cols-4">
        {% for meme in memes %}
        <div class="card col m-3 p-1 meme-width">
            <img src="{{url_for('memes.get_meme', meme_id=meme.id)}}" class="card-img-top" alt="{{meme.name}}">
            <div class="card-body">
                <a class="card-text btn stretched-link" href="{{url_for('memes.view_meme', meme_id=meme.id)}}">{{meme.name}}</a>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

memeapp/templates/meme.html
{% extends "base.html" %}
{% block title %}Dank Memes{% endblock %}
{% block body %}
<div class="container-fluid p-5">
    <h2>
        {{ meme.name}}
    </h2>
    <p class="d-inline-flex gap-1">
        <button class="btn btn-primary" type="button" data-bs-toggle="collapse" data-bs-target="#share"
                aria-expanded="false" aria-controls="share">
            Share
        </button>
    </p>
    <div class="collapse" id="share">
        <div class="card card-body form-control meme-width">
            <div class="input-group">
                <span class="input-group-text">Username</span>
                <input type="text" class="form-control" placeholder="Username" id="username" name="username">
                <button id="share-btn" class="btn btn-outline-secondary" type="button">Share</button>
            </div>
            <div class="alert alert-success d-none" role="alert" id="message">
                Shared successfully!
            </div>
        </div>
    </div>
    <br/>
    <div>
        <img src="{{url_for('memes.get_meme', meme_id=meme.id)}}" class="img-fluid">
    </div>
    <br/>
    <br/>
    <h2>Comments</h2>
    <hr/>
    <div>
        <div class="card card-body form-control meme-width>
            <div class="input-group">
                <span class="input-group-text">Title</span>
                <input type="text" class="form-control" placeholder="Title" id="title" name="title">
            </div>
            <div class="input-group">
                <span class="input-group-text">Comment</span>
                <textarea class="form-control" placeholder="Comment" id="body" name="body"></textarea>
            </div>
            <button id="submit-comment-btn" class="btn btn-outline-secondary" type="button">Submit</button>
        </div>
    </div>
    <div id="comments">
    </div>
    <script nonce="{{nonce}}">
        function shareMeme(e) {
            const username = document.querySelector("#username").value;

            fetch("{{url_for('memes.share_meme', meme_id=meme.id)}}", {
                method: "POST",
                mode: "cors",
                credentials: "same-origin",
                headers: {
                    "Content-Type": "application/json",
                },
                body: JSON.stringify({"username": username}),
            }).then(p => document.querySelector("#message").classList.remove("d-none"));
        }

        function getComments() {
            const commentsDiv = document.querySelector("#comments");
            commentsDiv.innerHTML = "";
            fetch("{{url_for('memes.comments', meme_id=meme.id)}}", {
                method: "GET",
                mode: "cors",
                credentials: "same-origin"
            }).then(p => p.json()).then((j) => {
                for (const comment of j['comments']) {
                    let div = document.createElement("div");
                    let h = document.createElement("h3");
                    let p = document.createElement("p");
                    div.classList.add("m-5");
                    div.classList.add("p-5");
                    div.classList.add("border");
                    h.innerHTML = `${comment["title"]} - <small class="text-muted"><a href="/users/${comment["author"]["id"]}">${comment["author"]["username"]}</a></small>`;
                    p.innerHTML = comment["body"];
                    div.appendChild(h);
                    div.appendChild(p);
                    commentsDiv.appendChild(div);
                }
            });
        }

        function submitComment(e) {
            const title = document.querySelector("#title").value;
            const body = document.querySelector("#body").value;

            fetch("{{url_for('memes.comments', meme_id=meme.id)}}", {
                method: "POST",
                mode: "cors",
                credentials: "same-origin",
                headers: {
                    "Content-Type": "application/json",
                },
                body: JSON.stringify({"title": title, "body":body}),
            }).then(p => getComments());
        }

        getComments();

        document.getElementById('share-btn').addEventListener("click", () => {
            shareMeme()
        });
        document.getElementById('submit-comment-btn').addEventListener("click", () => {
            submitComment()
        });
    </script>
</div>
{% endblock %}

memeapp/templates/shared.html
{% extends "base.html" %}
{% block title %}Dank Memes{% endblock %}
{% block body %}
<div class="container-fluid">
    <div class="row row-cols-4">
        {% for meme in memes %}
        <div class="card col m-3 p-1 meme-width">
            <img src="{{url_for('memes.get_meme', meme_id=meme.id)}}" class="card-img-top" alt="{{meme.name}}">
            <div class="card-body">
                <a class="card-text btn stretched-link" href="{{url_for('memes.view_meme', meme_id=meme.id)}}">{{meme.name}}</a>
                <p>Shared by {{meme.owner.name}} (<a href="{{url_for('users.get_user', user_id=meme.owner.id)}}}}" class="shared-by">{{meme.owner.username}}</a>)</p>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

memeapp/templates/upload.html
{% extends "base.html" %}
{% block title %}Dank Memes{% endblock %}
{% block body %}
<div class="container-fluid">
    <div class="row">
        <div class="col-3"></div>
        <div class="col-6">
            <form class="p-2 rounded-bottom" action="/upload" method="POST" enctype=multipart/form-data>
                <div class="mb-3">
                    <label for="name" class="form-label">Name</label>
                    <input type="text" class="form-control" id="name" name="name">
                </div>
                <div class="mb-3">
                    <div class="mb-3">
                        <label for="meme" class="form-label">Upload your meme:</label>
                        <input class="form-control" type="file" id="meme" name="file">
                    </div>
                </div>
                <button type="submit" class="btn btn-primary">Upload</button>
            </form>
        </div>
        <div class="col-3"></div>
    </div>
</div>
{% endblock %}